FROM local-base:latest

RUN uv pip --native-tls --allow-insecure-host pypi.org --allow-insecure-host files.pythonhosted.org install --system --upgrade pip setuptools wheel

ENV UV_HTTP_TIMEOUT=1000

# Copy just the pyproject.toml file to optimize caching
COPY web_search /app/web_search

WORKDIR /app/web_search

# Install the required Python packages using uv
RUN uv pip --native-tls --allow-insecure-host pypi.org --allow-insecure-host files.pythonhosted.org install --system .

# Copy the project code
# COPY web_search/project /app/web_search/project

# Set environment variables
ENV PYTHONPATH=/app

# Run the agent using uvicorn
CMD ["uvicorn", "project.acp:acp", "--host", "0.0.0.0", "--port", "8000"] 